/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ProjectID {
  id: string;
  description: string;
  categoryHint?: string;
}

export type TaskCategoryKey = 'ideacao' | 'gravacao' | 'construcao' | 'conducao' | 'agendas' | 'pos_producao';

export interface TaskCategoryDetail {
  key: TaskCategoryKey;
  label: string;
  color: string;
  bgColor: string;
  borderColor: string;
  subTasks: string[];
}

export interface HoursBreakdown {
  ideacao: number;
  gravacao: number;
  construcao: number;
  conducao: number;
  agendas: number;
  pos_producao: number;
  notes?: string;
}

export interface UserAllocation {
  person: string;
  allocations: {
    [projectId: string]: HoursBreakdown;
  };
}

export const TEAM_MEMBERS = [
  'AMANDA',
  'LUANA',
  'GABRIEL',
  'ANDREIA',
  'DAI',
  'DUA',
  'LAIZ',
  'NALU',
  'CLARISSA',
  'PEDRO',
  'GIU',
  'MONIQUE',
  'AUGUSTO',
  'LARISSA',
  'JESSICA P',
  'DUDA',
  'BEA',
  'LAURA',
  'EVE',
  'ANA BEATRIZ',
  'JESSICA T'
];

export const TASK_CATEGORIES: TaskCategoryDetail[] = [
  {
    key: 'ideacao',
    label: 'Ideação',
    color: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    subTasks: ['Preparação de materiais', 'Unidade do estudante', 'Pesquisa']
  },
  {
    key: 'gravacao',
    label: 'Gravação',
    color: 'text-rose-700',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    subTasks: ['Formação docente', 'Unidade do estudante', 'Vídeos orientativos', 'Acompanhamento de gravação']
  },
  {
    key: 'construcao',
    label: 'Construção de Materiais',
    color: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    subTasks: ['Formação docente', 'Notas de edição', 'Preenchimento de matrizes', 'Planos de aula', 'Exercícios', 'Avaliações']
  },
  {
    key: 'conducao',
    label: 'Condução Síncrona',
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    subTasks: ['Lives', 'Encontros formativos presenciais', 'Encontros formativos virtuais']
  },
  {
    key: 'agendas',
    label: 'Agendas',
    color: 'text-sky-700',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-200',
    subTasks: ['Alinhamento interno', 'Alinhamento com cliente', 'Validação interna', 'Validação externa']
  },
  {
    key: 'pos_producao',
    label: 'Pós-Produção',
    color: 'text-purple-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    subTasks: ['Upload de materiais', 'QA (Garantia de Qualidade)', 'Geração de links e arquivos']
  }
];

export const DEFAULT_PROJECTS: ProjectID[] = [
  { id: '3831', description: '[EFAI] Explorando padrões: uma aventura computacional' },
  { id: '3872', description: 'Investigando padrões: como os computadores aprendem' },
  { id: '3880', description: '[EFAI] Algoritmos: aventuras no labirinto com Luna e Cody' },
  { id: '3884', description: '[EFAI]Algoritmos: construindo sua história no StartLab' },
  { id: '3879', description: '[EFAI] Primeiros passos no computador: aprendendo sobre dispositivos de entrada e saída' },
  { id: '4070', description: '[Formação docente]' },
  { id: '4073', description: 'Lógica de programação: construindo uma jornada espacial' },
  { id: '4075', description: 'Introdução a python: desafios de programação' },
  { id: '4076', description: 'Ciência de dados: construindo uma análise de dados com Python' },
  { id: '4080', description: '[Formação docente]' },
  { id: '4082', description: '[Formação docente] Algoritmos: criando um jogo de pega-pega no StartLab' },
  { id: '4097', description: '[Formação docente]' },
  { id: '4098', description: '[Formação docente]' },
  { id: '4109', description: 'Tipos de dados: criando jogo de perguntas com onomatopeias' },
  { id: '4110', description: 'Laços de repetição: explorando narrativas indígenas em busca da palavra secreta' },
  { id: '4111', description: '[Matriz de referência]' },
  { id: '4112', description: 'Decomposição: desvendando o formato da terra' },
  { id: '4113', description: 'Estrutura de dados: programando a aventura do tesouro perdido' },
  { id: '4114', description: 'Lógica de programação: desenvolvendo a missão labirinto' },
  { id: '4115', description: 'Recursão: desenvolvendo arte geométrica com programação' },
  { id: '4116', description: 'Listas: construindo um jogo de cobrança de pênalti' },
  { id: '4117', description: 'Ordenando listas: brincando com dados estatísticos' },
  { id: '4118', description: 'Lista e Recursão: criando um projeto de fusão de personagens' },
  { id: '4119', description: 'Recursão: explorando formas geométricas com programação' },
  { id: '4120', description: 'Autômatos: criando uma simulação de um Robô em Marte' },
  { id: '4121', description: 'Decomposição: desenvolvendo um quiz sobre reciclagem' },
  { id: '4122', description: 'Projetos com programação: gerador inteligente de artigos' },
  { id: '4137', description: '[Formação docente]' },
  { id: '4138', description: '[Formação docente]' },
  { id: '4139', description: '[Formação docente]' },
  { id: '4140', description: '[Formação docente]' },
  { id: '4141', description: '[Formação docente]' },
  { id: '4142', description: '[Formação docente]' },
  { id: '4199', description: 'Projeto de vida: organizando objetivos futuros com matemática aplicada' },
  { id: '4202', description: 'Segurança digital: utilizando matemática para programar senhas seguras' },
  { id: '4212', description: '[Exercícios]' },
  { id: '4275', description: '[Formação docente]' },
  { id: '4280', description: '[Formação docente]' },
  { id: '4286', description: '[Formação docente]' },
  { id: '4287', description: '[Formação docente]' },
  { id: '4294', description: '[Formação docente]' },
  { id: '4295', description: '[Formação Docente] Conhecendo a plataforma Start para Anos Iniciais' },
  { id: '4296', description: '[Formação docente]' },
  { id: '4305', description: 'Entrada e saídas: criando um gênio virtual – Parte 1' },
  { id: '4306', description: 'Entrada e saídas: criando um gênio virtual' },
  { id: '4307', description: 'Decomposição: desvendando o formato da Terra (pt. 1)' },
  { id: '4308', description: 'Decomposição: desvendando o formato da Terra (pt. 2)' },
  { id: '4309', description: 'Listas: lógica e magia na programação - Parte 1' },
  { id: '4310', description: 'Listas: lógica e magia na programação - Parte 2' },
  { id: '4311', description: 'Recursão: desenvolvendo arte geométrica com programação' },
  { id: '4312', description: 'Recursão: desenvolvendo arte geométrica com programação - P2' },
  { id: '4313', description: 'Estrutura de dados: programando a aventura do tesouro perdido' },
  { id: '4314', description: 'Lógica de programação: desenvolvendo a missão labirinto' },
  { id: '4315', description: 'Estruturas de dados: programando a aventura do tesouro perdido (pt. 1)' },
  { id: '4316', description: 'Estrutura de dados: programando a aventura do tesouro perdido – Parte 2' },
  { id: '4330', description: '[Formação docente]' },
  { id: '4331', description: '[Formação docente]' },
  { id: '4334', description: 'Simulando a Cifra de César em JavaScript - P1' },
  { id: '4335', description: 'Cyberbullying: questionando comportamentos para promover empatia – Parte 1' },
  { id: '4336', description: 'Cyberbullying: questionando comportamentos para promover empatia – Parte 2' },
  { id: '4337', description: 'FORMAÇÃO DOCENTE' },
  { id: '4338', description: 'Formação Docente: educação midiática' },
  { id: '4342', description: '[Formação docente]' },
  { id: '4351', description: '[Formação docente]' },
  { id: '4352', description: '[Formação docente]' },
  { id: '4353', description: '[Formação Docente]' },
  { id: '4355', description: '[Formação Docente]' },
  { id: '4356', description: '[Formação docente]' },
  { id: '4358', description: '[Formação docente]' },
  { id: '4359', description: '[Formação docente]' },
  { id: '4360', description: '[Formação docente]' },
  { id: '4361', description: '[Formação docente]' },
  { id: '4362', description: '[Formação docente]' },
  { id: '4363', description: '[Formação docente]' },
  { id: '4364', description: 'Formação' },
  { id: '4365', description: 'FORMAÇÃO DOCENTE' },
  { id: '4366', description: 'AULA INAUGURAL PROF EFAF' },
  { id: '4367', description: 'AULA INAUGURAL PROF EM' },
  { id: '4372', description: 'Formação docente' },
  { id: '4373', description: 'Formação docente' },
  { id: '4375', description: '[Formação Docente]' },
  { id: '4376', description: '[Formação Docente]' },
  { id: '4386', description: 'AULA INAUGURAL ESTUDANTE' },
  { id: '4387', description: 'AULA INAUGURAL ESTUDANTE EM' },
  { id: '4399', description: 'Listas: construindo um jogo de cobrança de pênalti – Parte 1' },
  { id: '4400', description: 'Listas: construindo um jogo de cobrança de pênalti (pt2)' },
  { id: '4401', description: 'Modelo computacional: simulação com planilhas' },
  { id: '4482', description: 'FORMAÇÃO DOCENTE - Análise de dados: uma aventura com planilhas' },
  { id: '4483', description: '[Formação docente]' },
  { id: '4505', description: 'FORMAÇÂO' },
  { id: '4510', description: '[Matriz de referência]' },
  { id: '4528', description: 'Algoritmos: desenvolvendo jogos através da programação' },
  { id: '4550', description: 'Funções: criando uma missão sobre Inteligência Artificial' },
  { id: '4551', description: 'Técnicas computacionais: refletindo sobre Inteligência Artificial na escola' },
  { id: '4552', description: '[Formação docente]' },
  { id: '4553', description: 'Agrinho HTML e CSS' },
  { id: '4554', description: 'Agrinho JS' },
  { id: '4563', description: 'Decomposição: desenvolvendo um quiz sobre reciclagem' },
  { id: '4566', description: 'Agrinho - StartLab/Scratch' },
  { id: '4575', description: 'Abstração: resolução de problemas com Python' },
  { id: '4717', description: '[EFAI] Sequências: resolvendo problemas em etapas' },
  { id: '4718', description: '[EFAI] Máquinas: conhecendo tecnologias do dia a dia' },
  { id: '4719', description: '[EFAI] Repetições: máscaras que dançam' },
  { id: '4720', description: '[EFAI] Listas: o segredo das cartas perdidas' },
  { id: '4721', description: '[EFAI] Informação: criando mensagens em código' },
  { id: '4722', description: '[EFAI] Organizando o mundo' },
  { id: '4723', description: '[EFAI] Sequências: o algoritmo da vida' },
  { id: '4724', description: '[EFAI]' },
  { id: '4725', description: '[EFAI] Registros e organização de dados: uma investigação jornalística' },
  { id: '4726', description: '[EFAI]' },
  { id: '4727', description: '[EFAI]' },
  { id: '4728', description: '[EFAI]' },
  { id: '4729', description: '[EFAI]' },
  { id: '4730', description: '[EFAI]' },
  { id: '4731', description: '[EFAI] Algoritmos: missão supermercado' },
  { id: '4733', description: '[EFAI]' },
  { id: '4734', description: '[EFAI] Repetições: criando uma festa no StartLab' },
  { id: '5726', description: 'Algoritmos: criando um jogo de comandos no StartLab' },
  { id: '4735', description: '[EFAI]' },
  { id: '4736', description: '[EFAI]' },
  { id: '4738', description: 'OBI Estudantes' },
  { id: '4751', description: 'Robótica: utilizando tipos de dados com lógica' },
  { id: '4755', description: 'Curso técnico: Python - Capitulo 1' },
  { id: '4756', description: 'Nivelamento EF 1 - Introdutório (4 aulas)' },
  { id: '4757', description: 'Nivelamento EF 2 - Aprofundamento (4 aulas)' },
  { id: '4758', description: 'Cultura Digital: uma aventura no fórum com Cody' },
  { id: '4759', description: 'Cultura digital: segurança cibernética' },
  { id: '4760', description: 'Matemática (numero primo, divisivel, teste de mesa) 2 projetos' },
  { id: '4761', description: 'Recursão: com arte geométrica (projetos pequenos)' },
  { id: '4762', description: 'Educação Midiática: aprendendo a interagir com mídias digitais' },
  { id: '4763', description: 'Estrutura de dados: desenvolvendo um quiz sobre reciclagem' },
  { id: '4764', description: 'Autômatos (novo projeto)' },
  { id: '4765', description: 'Educação Midiática: o poder da informação' },
  { id: '4766', description: 'Nivelamento EM - Introdução à computação: tecnologias na sociedade do futuro' },
  { id: '4767', description: 'Página web: construindo flashcards de estudo com HTML e CSS' },
  { id: '4768', description: 'utilizar IA - apresentação.' },
  { id: '4769', description: 'FORMAÇÂO' },
  { id: '4770', description: '[Formação Docente]' },
  { id: '4802', description: '[Formação docente]' },
  { id: '4927', description: 'Lógica de Programação: jogos, arte e criatividade (Portugal)' },
  { id: '4928', description: '[Formação Docente] Lógica de Programação: jogos, arte e criatividade (Portugal)' },
  { id: '4939', description: '[Unidade nova] Educação midiática' },
  { id: '4976', description: 'Análise de dados: uma aventura exploratoria com Python' },
  { id: '4991', description: 'Curso técnico: Python - Capitulo 2' },
  { id: '4992', description: 'Curso técnico: Python - Capitulo 3' },
  { id: '4993', description: 'Curso técnico: Python - Capitulo 4' },
  { id: '4994', description: 'Curso técnico: Python - Capitulo 5' },
  { id: '4995', description: 'Curso técnico: Python - Capitulo 6' },
  { id: '4996', description: 'Curso técnico: Python - Capitulo 7' },
  { id: '4997', description: 'Curso técnico: Python - Capitulo 8' },
  { id: '5002', description: 'OBI Formação Docente' },
  { id: '5008', description: 'IA e Prompt - Capitulo 1' },
  { id: '5009', description: 'IA e Prompt - Capitulo 2' },
  { id: '5010', description: 'IA e Prompt - Capitulo 3' },
  { id: '5011', description: 'IA e Prompt - Capitulo 4' },
  { id: '5012', description: 'IA e Prompt - Capitulo 5' },
  { id: '5013', description: 'IA e Prompt - Capitulo 6' },
  { id: '5014', description: 'IA e Prompt - Capitulo 7' },
  { id: '5015', description: 'IA e Prompt - Capitulo 8' },
  { id: '5016', description: 'Projeto integrador 1 - Capitulo 1' },
  { id: '5017', description: 'Projeto integrador 1 - Capitulo 2' },
  { id: '5018', description: 'Projeto integrador 1 - Capitulo 3' },
  { id: '5019', description: 'Projeto integrador 1 - Capitulo 4' },
  { id: '5024', description: 'Ciência de dados - Capitulo 1' },
  { id: '5025', description: 'Ciência de dados - Capitulo 2' },
  { id: '5026', description: 'Ciência de dados - Capitulo 3' },
  { id: '5027', description: 'Ciência de dados - Capitulo 4' },
  { id: '5028', description: 'Ciência de dados - Capitulo 5' },
  { id: '5029', description: 'Ciência de dados - Capitulo 6' },
  { id: '5030', description: 'Ciência de dados - Capitulo 7' },
  { id: '5031', description: 'Ciência de dados - Capitulo 8' },
  { id: '5032', description: 'Projeto de IA e Dados - Capitulo 1' },
  { id: '5033', description: 'Projeto de IA e Dados - Capitulo 2' },
  { id: '5034', description: 'Projeto de IA e Dados - Capitulo 3' },
  { id: '5035', description: 'Projeto de IA e Dados - Capitulo 4' },
  { id: '5040', description: 'Front-End - Capitulo 1' },
  { id: '5041', description: 'Front-End - Capitulo 2' },
  { id: '5042', description: 'Front-End - Capitulo 3' },
  { id: '5043', description: 'Front-End - Capitulo 4' },
  { id: '5044', description: 'Front-End - Capitulo 5' },
  { id: '5045', description: 'Front-End - Capitulo 6' },
  { id: '5046', description: 'Front-End - Capitulo 7' },
  { id: '5047', description: 'Front-End - Capitulo 8' },
  { id: '5048', description: 'Projeto de DS - Capitulo 1' },
  { id: '5049', description: 'Projeto de DS - Capitulo 2' },
  { id: '5050', description: 'Projeto de DS - Capitulo 3' },
  { id: '5051', description: 'Projeto de DS - Capitulo 4' },
  { id: '5070', description: '[Formação docente] Introdução à lógica para o ensino de Computação' },
  { id: '5079', description: 'Robótica: simulando sinais de luz e som' },
  { id: '5080', description: 'Autômatos: criando sistemas inteligentes para o campo' },
  { id: '5090', description: '[Formação docente] Bootstrap para o Ensino de Computação' },
  { id: '5108', description: '[Formação docente] Sequências: resolvendo problemas em etapas' },
  { id: '5110', description: '[Formação docente] Repetições: máscaras que dançam' },
  { id: '5111', description: '[Formação docente] Listas: o segredo das cartas perdidas' },
  { id: '5112', description: 'Formação docente] Informação: criando mensagens em código' },
  { id: '5116', description: '[ Formação docente]' },
  { id: '5125', description: 'Simulados' },
  { id: '5204', description: '[Formação]' },
  { id: '5266', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade' },
  { id: '5271', description: 'Lógica de programação: jogos, arte e criatividade' },
  { id: '5273', description: 'Tipos de dados: criando uma coleção de máquinas' },
  { id: '5275', description: 'Blog com HTML/CSS pt 1' },
  { id: '5277', description: 'IA: utilizando dados para tomar decisões' },
  { id: '5278', description: 'Segurança digital com criptografia em python' },
  { id: '5279', description: 'Listas com penalti, ou outra temática.' },
  { id: '5280', description: 'Laços de repetição: explorando narrativas indígenas em busca da palavra secreta' },
  { id: '5282', description: 'Robótica nova unidade 1' },
  { id: '5283', description: 'Lógica de programação: nivelamento python' },
  { id: '5284', description: 'Robótica nova unidade 3' },
  { id: '5285', description: 'Autômatos' },
  { id: '5286', description: 'Blog com HTML/CSS pt 2' },
  { id: '5287', description: 'IA em projetos' },
  { id: '5288', description: 'Comparar interfaces e UX. acessibilidade' },
  { id: '5289', description: 'Estratégias Computacionais: resolvendo problemas matemáticos' },
  { id: '5290', description: 'Listas: lógica e magia na programação / add cortes e glossário' },
  { id: '5293', description: 'LLM em projetos' },
  { id: '5298', description: 'Python: Modelos computacionais avançado' },
  { id: '5300', description: 'Lógica de programação: exploração criativa' },
  { id: '5302', description: 'Robótica: construindo um robô protetor' },
  { id: '5304', description: 'Cyberbullying: questionando comportamentos para promover empatia' },
  { id: '5306', description: 'Inteligência Artificial: resolução de problemas' },
  { id: '5307', description: 'Robótica: construindo um protótipo de parquinho com Servo Motor' },
  { id: '5309', description: 'Lógica de programação: criando arte interativa com P5.js' },
  { id: '5310', description: 'Listas, funções e repetição: criando um jogo de corrida' },
  { id: '5311', description: 'Introdução a python - desafios de programação' },
  { id: '5312', description: 'Ciência de dados: construindo uma análise de dados com Python' },
  { id: '5313', description: 'Soluções criativas: criando a interface de uma rede social' },
  { id: '5316', description: 'Mundo do trabalho: iniciando sua jornada profissional' },
  { id: '5314', description: 'Modelo computacional: simulação com planilhas' },
  { id: '5321', description: 'Formação docente' },
  { id: '5322', description: 'Formação docente' },
  { id: '5345', description: 'Algoritmos: criando um jogo de pega-pega no StartLab' },
  { id: '5348', description: 'Formação StartEduca+' },
  { id: '5351', description: 'Página Web: criando um catálogo de vídeos com HTML e CSS' },
  { id: '5352', description: 'Algoritmos: criando uma aventura com HTML, CSS e JavaScript' },
  { id: '5372', description: 'Segurança Cibernética: práticas para proteção digital parte 1' },
  { id: '5373', description: 'Lógica de programação: jogos, arte e criatividade parte 1' },
  { id: '5273', description: 'Tipos de dados: criando uma coleção de máquinas' },
  { id: '5375', description: 'Educação Midiática: o poder da informação parte 1' },
  { id: '5376', description: 'Introdução à computação: conhecendo o teclado e o mouse' },
  { id: '5377', description: 'Introdução à computação: explorando recursos de edição de texto' },
  { id: '5378', description: 'Nivelamento 9 ano - Redes sociais: conteúdo que se conecta com algoritmos' },
  { id: '5379', description: 'Modelo Computacional: Simulação com planilhas parte 1' },
  { id: '5380', description: 'Modelo Computacional: Simulação com planilhas parte 2' },
  { id: '5422', description: 'Funções: criando uma missão sobre Inteligência Artificial' },
  { id: '5423', description: 'Segurança digital: utilizando matemática para programar senhas seguras' },
  { id: '5425', description: 'Segurança digital com criptografia em python parte 1' },
  { id: '5426', description: 'Lógica de programação: exploração criativa parte 2' },
  { id: '5427', description: 'Segurança Cibernética: práticas para proteção digital parte 2' },
  { id: '5428', description: 'Lógica de programação: jogos, arte e criatividade parte 2' },
  { id: '5429', description: 'Introdução a python - desafios de programação parte 1' },
  { id: '5430', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade parte 2' },
  { id: '5504', description: 'Educação Midiática: aprendendo a interagir com mídias digitais parte 1' },
  { id: '5530', description: 'IA: refletindo sobre qualidade, relevância e precisão das fontes digitais' },
  { id: '5350', description: 'Projeto de vida: organizando objetivos futuros com matemática aplicada' },
  { id: '5464', description: '[FD] Inteligência Artificial: Resolvendo problemas' },
  { id: '5113', description: '[Formação docente] Registros e organização de dados: uma investigação jornalística' },
  { id: '5317', description: '[FD] Introdução à computação iniciando meus estudos' },
  { id: '5109', description: '[Formação docente] Máquinas: Conhecendo tecnologias do dia a dia' },
  { id: '4294', description: '[FD] Conhecendo a plataforma Start: Anos Iniciais' },
  { id: '5318', description: '[FD] Introdução á computação: aprofundando meus estudos' },
  { id: '5496', description: '[Formação docente] Repetição: criando uma festa no StartLab' },
  { id: '5320', description: '[FD] Segurança Cibernética: práticas para proteção digital' },
  { id: '5463', description: '[FD] Segurança Cibernética: práticas para proteção digital' },
  { id: '5495', description: '[FD] Conhecendo a plataforma' },
  { id: '5324', description: '[FD] Introdução à computação: tecnologias na sociedade do futuro' },
  { id: '5319', description: '[FD] Cultura Digital: uma aventura no fórum com Cody' },
  { id: '5454', description: '[FD] Robótica: simulando sinais de luz e som' },
  { id: '5455', description: '[FD] Mídias digitais: sua apresentação com autorIA' },
  { id: '5492', description: '[FD] Redes sociais: conteúdo que se conecta com algoritmos' },
  { id: '5616', description: '[FD]' },
  { id: '5654', description: '[FD] Autômatos: criando sistemas inteligentes para o campo' },
  { id: '5716', description: '[FD]' },
  { id: '5718', description: '[FD]' },
  { id: '4294', description: '[FD] Conhecendo a Plataforma Start Anos Iniciais' },
  { id: '5561', description: 'IA e prompt - Capítulo 1' },
  { id: '5493', description: '[FD] Introdução à computação: explorando recursos de edição de texto' },
  { id: '5374', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade parte 1' },
  { id: '5371', description: 'Lógica de programação: exploração criativa parte 1' },
  { id: '5637', description: 'Primeiros passos em Python' },
  { id: '5656', description: 'Introdução à computação: conhecendo o teclado e o mouse' },
  { id: '5294', description: 'Decomposição' },
  { id: '5642', description: 'Introdução à computação: aprofundando meus estudos' },
  { id: '5644', description: 'Introdução à computação: explorando recursos de edição de texto' },
  { id: '5613', description: 'Introdução à computação: iniciando meus estudos' },
  { id: '5613', description: 'Introdução à computação: tecnologias na sociedade do futuro' },
  { id: '5675', description: 'Lógica de programação: criando arte interativa com P5.js' },
  { id: '5649', description: 'Lógica de programação: exploração criativa parte 1' },
  { id: '5664', description: 'Lógica de programação: jogos, arte e criatividade parte 1' },
  { id: '5707', description: '[Formação Docente] Primeiros passos no computador: aprendendo sobre dispositivos de entrada e saída' },
  { id: '5711', description: '[Formação Docente] Algoritmos: aventuras no labirinto com Luna e Cody' },
  { id: '5712', description: '[Formação Docente] Algoritmos: construindo sua história no StartLab' },
  { id: '5715', description: '[Formação Docente] Ciência de dados' },
  { id: '5709', description: '[Formação Docente] Explorando padrões: uma aventura computacional' },
  { id: '5641', description: 'Mídias digitais: sua apresentação com autorIA' },
  { id: '5642', description: 'Introdução à computação: aprofundando meus estudos' },
  { id: '5644', description: 'Introdução à computação: explorando recursos de edição de texto' },
  { id: '5645', description: 'Redes sociais: conteúdo que se conecta com algoritmos' },
  { id: '5646', description: 'Introdução à computação: tecnologias na sociedade do futuro' },
  { id: '5656', description: 'Introdução à computação: conhecendo o teclado e o mouse' },
  { id: '5657', description: 'Segurança Cibernética: práticas para proteção digital parte 1' },
  { id: '5675', description: 'Lógica de programação: criando arte interativa com P5.js' },
  { id: '5682', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade parte 1' },
  { id: '5691', description: 'Educação Midiática: o poder da informação parte 1' },
  { id: '5821', description: 'Listas, funções e repetição: criando um jogo de corrida parte 1' },
  { id: 'S/ID', description: 'Avaliações diagnósticas Seduc' },
  { id: '5786', description: 'Algoritmos: construindo um jogo com variáveis' },
  { id: '5787', description: 'Operadores lógicos: resolvendo mistérios e criando fluxogramas' },
  { id: '5770', description: 'Primeiros passos no computador: aprendendo sobre dispositivos de entrada e saída' },
  { id: '5771', description: 'Explorando padrões: uma aventura computacional' },
  { id: '5782', description: '[Formação docente] Investigando padrões: como os computadores aprendem' },
  { id: '5774', description: 'Investigando padrões: como os computadores aprendem' },
  { id: '5643', description: 'Cultura Digital: uma aventura no fórum com Cody' },
  { id: '4748', description: '[EFAI]' },
  { id: '4732', description: '[EFAI]' },
  { id: '5786', description: '[EFAI]' },
  { id: '5785', description: '[EFAI]' },
  { id: '5683', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade' },
  { id: '5651', description: 'Tipos de dados: criando uma coleção de máquinas' },
  { id: '5658', description: 'Segurança Cibernética: práticas para proteção digital' },
  { id: '5659', description: 'Análise de algoritmos: debugando a lógica do número primo' },
  { id: '5669', description: 'Educação Midiática: o poder da informação' },
  { id: '5665', description: 'Lógica de programação: jogos, arte e criatividade' },
  { id: '5670', description: 'O uso da IA para compreender e transformar realidades sociais' },
  { id: '5676', description: 'Modelo Computacional: Simulação com planilhas' },
  { id: '5677', description: 'Introdução a python : desafios de programação' },
  { id: '5683', description: 'Planilhas: analisando dados sobre acessibilidade na sua comunidade' },
  { id: '6032', description: 'Agrinho 2026 - Programação em blocos' },
  { id: '6033', description: 'Agrinho 2026 - Front-End' },
  { id: '5667', description: 'Algoritmos clássicos: ordenação de lista com python 8 ano' },
  { id: '5779', description: 'Projeto de DS - Capítulo 1' },
  { id: '5689', description: 'Recursão: desenhando padrões que se repetem' },
  { id: '5690', description: 'IA: refletindo sobre qualidade, relevância e precisão das fontes digitais' },
  { id: '5772', description: '[EFAI]' },
  { id: '5296', description: 'Fundamentos de criptografia: implementando cifras em Python' },
  { id: '5292', description: 'Algoritmos clássicos: ordenação de lista com python' },
  { id: '5832', description: 'Listas: lógica e magia na programação parte 1' },
  { id: '5833', description: 'Listas: lógica e magia na programação parte 2' },
  { id: '5773', description: 'Algoritmos: construindo sua história no StartLab' },
  { id: '5301', description: 'Entrada e saídas: criando um gênio virtual' },
  { id: '5779', description: 'Projeto de DS - Capítulo 1' },
  { id: '6336', description: 'Currículo Start 2027' },
  { id: '6041', description: 'FD - Robótica: utilizando sensores para promover acessibilidade e inclusão' },
  { id: '6044', description: 'FD -Autômatos: lógica de estados em histórias interativas' },
  { id: '5984', description: 'FD -Tipos de dados: criando uma coleção de máquinas' },
  { id: '5651', description: 'Tipos de dados: criando uma coleção de máquinas' },
  { id: '4372', description: 'FD - Laços de repetição explorando narrativas indígenas em busca da palavra secreta' },
  { id: '6050', description: 'FD - Matrizes: caça ao tesouro com coordenadas' }
];
